---
title: "Data Science and Predictive Analytics (UMich HS650)"
subtitle: "<h2><u>Assignment 1: R Foundations</u></h2>"
author: "<h3>SOCR/MIDAS (Ivo Dinov)</h3>"
date: "`r format(Sys.time(), '%B %Y')`"
tags: [DSPA, SOCR, MIDAS, Big Dta, Predictive Analytics] 
output:
  html_document:
    theme: spacelab
    highlight: tango
    includes:
      before_body: SOCR_header.html
      after_body: SOCR_footer_tracker.html
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
---


#	Confirm that you have installed R/RStudio

You should be able to download and load in RStudio the [Foundations of R code](http://www.socr.umich.edu/people/dinov/courses/DSPA_notes/01_Foundation.R). Then run all the examples.


# Long-to-Wide Data format translation
Load in [the long-format SOCR Parkinson's Disease data](http://wiki.socr.umich.edu/index.php/SOCR_Data_PD_BiomedBigMetadata#Data_Table) and export it as *wide format*. You can only do 5 variables you choose (not all), but note that there are several time observations for each subject. You can try using the `reshape` command. 

# Data Frames
Create a Data Frame of [the SOCR Parkinson's Disease data](http://wiki.socr.umich.edu/index.php/SOCR_Data_PD_BiomedBigMetadata#Data_Table) and compute a summary of 3 features you select.

# Data stratification	
Using the [same SOCR Parkinson's Disease data](http://wiki.socr.umich.edu/index.php/SOCR_Data_PD_BiomedBigMetadata#Data_Table):

* Extract the first 10 subjects
* Find the cases for which `L_caudate_ComputeArea<600`. 	
* Sort the subjects based on `L_caudate_Volume`.
* Gernerate frequency and probability tables for `Gender` and `Age`.
* Compute the mean `Age` and the correlation between `Age` and `Weight`.
* Plot Histogram and density of `R_fusiform_gyrus_Volume` and scatterplot `L_fusiform_gyrus_Volume` and `R_fusiform_gyrus_Volume`.

Note: You don't have to apply these data filters sequentially, but this can also be done for deeper stratification.
 
# Simulation

Generate 1,000 standard normal variables and 1,200 Cauchy distributed random variables and generate a quantile-quantile (Q-Q) probability plot of the pair of samples.


# Programming

Generate an `R` function that computes the arithmetic average and compare it against the `mean()` function.
