---
title: "Data Science and Predictive Analytics (UMich HS650)"
subtitle: "<h2><u>Assignment 9: Forecasting Numeric Data using Regression Models</u></h2>"
author: "<h3>SOCR/MIDAS (Ivo Dinov)</h3>"
date: "`r format(Sys.time(), '%B %Y')`"
tags: [DSPA, SOCR, MIDAS, Big Dta, Predictive Analytics] 
output:
  html_document:
    theme: spacelab
    highlight: tango
    includes:
      before_body: SOCR_header.html
      after_body: SOCR_footer_tracker.html
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Regression Forecasting for Numerical Data 

Use the [Quality of Life data (Case06_QoL_Symptom_ChronicIllness)](https://umich.instructure.com/courses/38100/files/folder/Case_Studies) to fit several different Multiple Linear Regression models predicting clinically relevant outcomes, e.g., `Chronic Disease Score`.

* Summarize and visualize the data using `summary`, `str`, `pairs.panels`, `ggplot`.
* Report paired correlations for numeric data and try to visualize these (e.g., heatmap, pairs plot, etc.)
* Examine potential dependencies of the predictors and the dependent response variables
* Fit a Multiple Linear Regression model, report the results, and explain the summary, residuals, effect-size coefficients, and the coefficient of determination, $R^2$
* Draw model diagnostic plots, at least QQ plot, residuals plot and leverage plot (half norm plot)
* Predict outcomes for new data
* Try to improve the model performance using `step` function based on AIC and BIC.
* Fit a regression tree model and compare with OLS model.
* Try to use `M5P` to improve the model.