---
title: "Data Science and Predictive Analytics (UMich HS650)"
subtitle: "<h2><u>Assignment 11: Apriori Association Rules Learning</u></h2>"
author: "<h3>SOCR/MIDAS (Ivo Dinov)</h3>"
date: "`r format(Sys.time(), '%B %Y')`"
tags: [DSPA, SOCR, MIDAS, Big Dta, Predictive Analytics] 
output:
  html_document:
    theme: spacelab
    highlight: tango
    includes:
      before_body: SOCR_header.html
      after_body: SOCR_footer_tracker.html
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
---

#  Use the SOCR Jobs Data to practice Apriori Association Rule learning

* [Load the Jobs Data](http://wiki.socr.umich.edu/index.php/SOCR_Data_2011_US_JobsRanking])
* [Use this guide to load HTML data data](http://wiki.socr.umich.edu/index.php/SMHS_EDA#Loading_HTML_data_in_R)
* Focus on the *Description* feature. Replace all underscore characters "_" with spaces
* Save the data using `write.csv()` and then use the `read.transactions()` in `arules` package to read the CSV data file. Visualize the item support using item frequency plots
* Generate the sparse terms matrix for each job category. What terms appear as more popular?
* Fit a model: `myrules<-apriori(data=jobs,parameter=list(support=0.1,confidence=0.8,minlen=1))`. Try out several rule thresholds trading off gain and accuracy
* Evaluate model performance with `lift`
* Try to improve the model performance
* Sort the set of association rules
* Investigate associations that may be linked to a specific job-description terms.