---
title: "Data Science and Predictive Analytics (UMich HS650)"
subtitle: "<h2><u>Assignment 12: k-Means Clustering</u></h2>"
author: "<h3>SOCR/MIDAS (Ivo Dinov)</h3>"
date: "`r format(Sys.time(), '%B %Y')`"
tags: [DSPA, SOCR, MIDAS, Big Data, Predictive Analytics] 
output:
  html_document:
    theme: spacelab
    highlight: tango
    includes:
      before_body: SOCR_header.html
      after_body: SOCR_footer_tracker.html
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Amyotrophic Lateral Sclerosis (ALS) Case-Study

Use the [ALS dataset](https://umich.instructure.com/courses/38100/files/folder/Case_Studies/15_ALS_CaseStudy). This case-study examines the patterns, symmetries, associations and causality in a rare but devastating progressive neurodegenerative disease, amyotrophic lateral sclerosis (ALS). Major clinically relevant questions include: *What patient phenotypes can be automatically and reliably identified and used to predict the change of the ALSFRS slope over time?*

* Load and prepare the data
* report data summary and show some preliminary visualizations
* Train a **k-Means** model on the data, select $k$ according to the guide in [Chapter 12 notes](http://www.socr.umich.edu/people/dinov/courses/DSPA_notes/12_kMeans_Clustering.html)
* Evaluate the model performance using *bar* and *silhouette* plots and summarize the results
* Tune and plot parameters with **k-means++**
* Rerun the model with the optimal parameters and interpret the clustering results
* Apply *Hierarchical Clustering* on three different linkages and compare the corresponding *silhouette* plots
* Fit a Gaussian mixture model, select the optimal model, report *BIC*, and display density and classification plots
* Compare the result of the above methods

You can also try this protocol on some additional datasets from the list of our [Case-Studies](https://umich.instructure.com/courses/38100/files/).