---
title: "Data Science and Predictive Analytics (UMich HS650)"
subtitle: "<h2><u>Assessment: 16. Variable/Feature Selection</u></h2>"
author: "<h3>SOCR/MIDAS (Ivo Dinov)</h3>"
date: "`r format(Sys.time(), '%B %Y')`"
tags: [DSPA, SOCR, MIDAS, Big Dta, Predictive Analytics] 
output:
  html_document:
    theme: spacelab
    highlight: tango
    includes:
      before_body: SOCR_header.html
      after_body: SOCR_footer_tracker.html
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Wrapper feature selection

* Explain the [three major types of feature selection methods](https://en.wikipedia.org/wiki/Feature_selection#Main_principles)
    + Filter
    + Wrapper
    + Embedded

# Feature Selection in Parkinson's Disease (PPMI Data)

Use the [06_PPMI_ClassificationValidationData_Short dataset](https://umich.instructure.com/courses/38100/files/folder/data?) setting `ResearchGroup` as class variable.

* Delete irrelevant columns (e.g. `X`, `FID_IID`) and select only the *PD* and *Control* cases
* Properly convert the variables types
* Apply `Boruta` to train a model, try different parameters (e.g., try different `pValue`, `maxRuns`). What are the differences?
* Summarize and visualize the results
* Apply *Random Feature Elimination* (RFE) and tune the model size
* Evaluate the `Boruta` model performance by comparing with REF
* Report and compare the variables selected by both methods. How much overlap is there in the selected variables?