---
title: "Data Science and Predictive Analytics (UMich HS650)"
subtitle: "<h2><u>Assessment: 17. Regularized Linear Modeling and Knockoff Filtering</u></h2>"
author: "<h3>SOCR/MIDAS (Ivo Dinov)</h3>"
date: "`r format(Sys.time(), '%B %Y')`"
tags: [DSPA, SOCR, MIDAS, Big Dta, Predictive Analytics] 
output:
  html_document:
    theme: spacelab
    highlight: tango
    includes:
      before_body: SOCR_header.html
      after_body: SOCR_footer_tracker.html
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Regularized Linear Modeling and Controlled Variable Selection (Knockoff Filtering)

Use the [Hearth Attack (CaseStudy12_ AdultsHeartAttack) data](https://umich.instructure.com/files/330397/download?download_frd=1) to:

* Identify and impute any missing values
* Use the `DIAGNOSIS` as a clinically relevant outcome variable
* Randomly split the data into training (70%) and testing (30%) sets
* Use the LASSO model to standardize the predictors and report the model results
* Optimize the choice of the regularization parameter
* Apply cross validation to report internal statistical validity of the model
* Report and compare the OLS, Stepwise OLS with AIC, Ridge and LASSO coefficient estimates
* Calculate the predicted values for all 4 models and report the models performance
* Apply knockoff filtering to control the false variable selection rate
* Compare the variables selected by Stepwise OLS, LASSO and knockoff
* Apply Bootstrap LASSO and knockoff, and compare the results.