---
title: "Data Science and Predictive Analytics (UMich HS650)"
subtitle: "<h2><u>Assessment: 19. Natural Language Processing/Text Mining</u></h2>"
author: "<h3>SOCR/MIDAS (Ivo Dinov)</h3>"
date: "`r format(Sys.time(), '%B %Y')`"
tags: [DSPA, SOCR, MIDAS, Big Dta, Predictive Analytics] 
output:
  html_document:
    theme: spacelab
    highlight: tango
    includes:
      before_body: SOCR_header.html
      after_body: SOCR_footer_tracker.html
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Mining Twitter Data
Use these [R Data Mining Twitter data](http://www.rdatamining.com/data) to apply NLP/TM methods and investigate the Twitter corpus.

* Construct a VCorpus object
* Clean the VCorpus object
* Build document-term matrix (DTM)
* Compute the TF-IDF(term frequency - inverse document frequency
* Use the DTM to construct a wordcloud.

# Mining Cancer Clinical Notes

Use [Head and Neck Cancer Medication Data](https://umich.instructure.com/files/1614350/download?download_frd=1) to to apply NLP/TM methods and investigate the information content. In  [Chapter 7](http://www.socr.umich.edu/people/dinov/courses/DSPA_notes/07_NaiveBayesianClass.html), we already saw some preliminary TM analysis. Now we need to go further.

* Use `MEDICATION_SUMMARY` to construct a VCorpus object
* Clean the VCorpus object
* Build a document term matrix (DTM)
* Add a column to indicate early and later cancer stage according to `seer_stage` (refer to [Chapter 7](http://www.socr.umich.edu/people/dinov/courses/DSPA_notes/07_NaiveBayesianClass.html))
* Use the DTM to construct a wordcloud for early stage, later stage and the entire dataset
* Interpret the wordclouds
* Compute the TF-IDF (Term Frequency - Inverse Document Frequency)
* Apply LASSO on the unweighted and weighted DTM respectively and evaluate the results according to AUC
* Try the cosine similarity transformation, apply LASSO, and compare the results
* Use other measures such as "class" for `cv.glmnet()`
* Does it appear that these classifiers may provide an automated machine interpretation of unstructured free text?