---
title: "Data Science and Predictive Analytics (UMich HS650)"
subtitle: "<h2><u>Assessment 20: Prediction and Internal Statistical Cross Validation</u></h2>"
author: "<h3>SOCR/MIDAS (Ivo Dinov)</h3>"
date: "`r format(Sys.time(), '%B %Y')`"
tags: [DSPA, SOCR, MIDAS, Big Data, Predictive Analytics] 
output:
  html_document:
    theme: spacelab
    highlight: tango
    includes:
      before_body: SOCR_header.html
      after_body: SOCR_footer_tracker.html
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
---

Using the following two case-studies independently:

* Example 1: [ALS (Amyotrophic Lateral Sclerosis)](https://umich.instructure.com/courses/38100/files/folder/Case_Studies/15_ALS_CaseStudy)
* Example 2: [Quality of Live in Chronic Illness (Case06_QoL_Symptom_ChronicIllness.csv)](https://umich.instructure.com/courses/38100/files/folder/Case_Studies)

Construct and test the following protocol:

* Review each case-study
* Choose appropriate dichotomous, polytomous, or continuous outcome variables, e.g., use `ALSFRS_slope` for ALS, `CHRONICDISEASESCORE` for *case 06* and cast as an outcome dichotomous outcome
* Apply appropriate data preprocessing
* Perform regression modeling for continuous outcomes
* Perform classification and prediction using various methods (LDA, QDA, AdaBoost, SVM, Neural Network, KNN) for discrete outcomes
* Apply cross-validation on these regression and classification methods, respectively
* Report standard error for regression approaches
* Report appropriate quality metrics that can be used to rank the forecasting approaches based on the predictive power of the corresponding prediction/classification results
* Compare the results of model-driven and data-driven (e.g., KNN) methods
* Compare sensitivity and specificity, respectively
* Use unsupervised clustering methods (e.g., *k-Means*) and spectral clustering
* Evaluate and justify *k-Means* model and detect how agreement of the clusters with labels
* Report the classification error of *k-means* and compare it against the result of *k-means++*.