---
title: "Data Science and Predictive Analytics (UMich HS650)"
subtitle: "<h2><u>Assessment: 22. Deep Learning, Neural Networks</u></h2>"
author: "<h3>SOCR/MIDAS (Ivo Dinov)</h3>"
date: "`r format(Sys.time(), '%B %Y')`"
tags: [DSPA, SOCR, MIDAS, Big Data, Predictive Analytics] 
output:
  html_document:
    theme: spacelab
    highlight: tango
    includes:
      before_body: SOCR_header.html
      after_body: SOCR_footer_tracker.html
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Deep learning Classification

* Download the [SOCR Alzheimer's disease data](http://wiki.socr.umich.edu/index.php/SOCR_Data_July2009_ID_NI)
* Preprocess the data and pool the `MCI` and `AD` cohorts (patients)
* Build a multi-layer perceptron as a classifier (patients vs. controls) and select proper parameters
* Classify `AD` and `NC` and report detailed evaluations, including cross table, accuracy, sensitivity, specificity, LOR, AUC
* Provide some visualizations, e.g., histogram and model structure graph as we did in [Chapter 22](http://www.socr.umich.edu/people/dinov/courses/DSPA_notes/22_DeepLearning.html)
* Then, try to perform a multi-classes modeling (i.e., `AD`, `NC` and `MCI`) and report the classification results.

# Deep learning Regression

* Download the [Allometric relationship data](http://wiki.socr.umich.edu/index.php/SOCR_Data_Dinov_032708_AllometricPlanRels) from the SOCR data archive
* Preprocess the data and set `density` as outcome response feature
* Create a `MXNet` feed-forward neural net model and properly specify the parameters
* Train and predict the density using this model and report RMSE on the test data, evaluate the result and justify your evaluation
* Output the model structure.

# Image classification

Apply the deep learning neural network techniques to classify some images with pre-trained model as we did in [Chapter 22](http://www.socr.umich.edu/people/dinov/courses/DSPA_notes/22_DeepLearning.html):

* [Google images](https://www.google.com/search?safe=active&biw=1152&bih=728&tbm=isch&q=image)
* [SOCR Neuroimaging data](http://wiki.socr.umich.edu/index.php/SOCR_Data#Neuroimaging_Data)
* Or using your own images.